/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

--drop schema if exists "proc" cascade;

--CREATE SCHEMA if not exists "proc";
{{ template "actor_create_proc.sql".}} 
{{ template "actor_update_proc.sql".}} 
{{ template "actor_delete_proc.sql".}} 
{{ template "actor_undo_delete_proc.sql".}} 
{{ template "activitymodel_create_proc.sql".}} 
{{ template "activitymodel_update_proc.sql".}} 
{{ template "activitymodel_delete_proc.sql".}} 
{{ template "activitymodel_undo_delete_proc.sql".}} 
{{ template "activitymodelversion_create_proc.sql".}} 
{{ template "activitymodelversion_update_proc.sql".}} 
{{ template "activitymodelversion_delete_proc.sql".}} 
{{ template "activitymodelversion_undo_delete_proc.sql".}} 
{{ template "activity_create_proc.sql".}} 
{{ template "activity_update_proc.sql".}} 
{{ template "activity_delete_proc.sql".}} 
{{ template "activity_undo_delete_proc.sql".}} 
{{ template "event_create_proc.sql".}} 
{{ template "event_update_proc.sql".}} 
{{ template "event_delete_proc.sql".}} 
{{ template "event_undo_delete_proc.sql".}} 
{{ template "activityversion_create_proc.sql".}} 
{{ template "activityversion_update_proc.sql".}} 
{{ template "activityversion_delete_proc.sql".}} 
{{ template "activityversion_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 

